// 小狗的闲聊台词：没人点它时每 12 秒挑一句。{circled}、{best} 会换成今天的数字；{kid} 是孩子的名字。
// remember 是「记得你」：{fixed} 昨天订正对几题、{focus} 这周重点组名、{days} 陪伴天数。need 写了的，那个数是 0 时不说。
export const LINES = {
  idle: [
    {t: "云朵像不像一个大馒头？我闻闻……", act: "sniff"},
    {t: "我刚才数了数，我有两只耳朵，一个不少！", act: "giggle"},
    {t: "如果袜子会说话，它会不会喊脚好臭？", act: "giggle"},
    {t: "嗯……蜗牛搬家要走多久呢？", act: "think"},
    {t: "伸个大懒腰——咔咔咔，骨头在唱歌！", act: "stretch"},
    {t: "我转一圈，你猜我晕不晕？", act: "spin"},
    {t: "眨眨眼，我在给你发摩斯密码哦", act: "blink"},
    {t: "那边好像有只小虫子，嘘——", act: "look"},
    {t: "我想学跳绳，可是绳子总缠住我的脚……", act: "hop"},
    {t: "嗨！我刚刚想到一个笑话，又忘了。", act: "wave"},
    {t: "打个哈欠——啊呜，把空气吃掉一口", act: "yawn"},
    {t: "月亮白天去哪儿了？是不是在睡觉？", act: "think"},
    {t: "跳一跳，看我能不能碰到天花板！", act: "hop"},
    {t: "我今天的发型是不是有点乱乱的？", act: "look"},
  ],
  math: [
    {t: "晚上9时半就是21:30，我该钻被窝啦", act: "sleepy"},
    {t: "下午3时就是15时，加上12就对啦", act: "think"},
    {t: "从8:00到8:40，经过了40分钟哦", act: "look"},
    {t: "每隔2分钟敲一下，第1下到第4下隔6分钟", act: "hop"},
    {t: "一排种5棵树，中间只有4个空隙呢", act: "think"},
    {t: "有括号的先算括号里，我记牢啦", act: "blink"},
    {t: "我吃了3个苹果，答案后面要带上“个”", act: "giggle"},
    {t: "读题我要读两遍，慢慢来不着急", act: "think"},
  ],
  state_hungry: [
    {t: "肚子咕咕叫，能给我一块骨头饼干吗？", act: "sniff"},
    {t: "我闻到好吃的味道了，可以分我一口吗？", act: "sniff"},
    {t: "有空喂我吃点东西好不好呀？", act: "look"},
  ],
  state_bored: [
    {t: "我们一起玩个小游戏好不好？", act: "hop"},
    {t: "陪我转个圈圈吧，一个人转好无聊", act: "spin"},
    {t: "有空的时候，来逗逗我嘛", act: "wave"},
  ],
  state_dirty: [
    {t: "我身上有点脏脏的，能帮我洗个澡吗？", act: "look"},
    {t: "泡泡浴！我想要好多好多泡泡！", act: "hop"},
    {t: "我闻闻自己……嗯，该洗洗啦", act: "sniff"},
  ],
  time_morning: [
    {t: "早上好！太阳公公也刚起床呢", act: "stretch"},
    {t: "早呀！今天吃早饭了吗？", act: "wave"},
  ],
  time_evening: [
    {t: "天黑啦，星星在一颗一颗地亮起来", act: "look"},
    {t: "晚饭吃了什么呀？我好想闻一闻", act: "sniff"},
  ],
  time_late: [
    {t: "我困啦，要去睡觉了，晚安哦！", act: "sleepy"},
    {t: "啊呜……明天见，祝你做个甜甜的梦", act: "yawn"},
  ],
  after_practice: [
    {t: "你圈了{circled}次关键词，读题好仔细！", act: "hop"},
    {t: "连着{best}题一次做对，是认真读题的功劳", act: "spin"},
    {t: "今天圈了{circled}次关键词，你一步一步来的", act: "giggle"},
    {t: "{best}题连着做对，你写得稳稳当当的", act: "wave"},
  ],
  remember: [
    {t: "{kid}，昨天你订正对了 {fixed} 道题，我都看见了。", act: "hop", need: "fixed"},
    {t: "这周我们一起练「{focus}」，慢慢来就好。", act: "think", need: "focus"},
    {t: "我们已经一起过了 {days} 天啦，{kid}！", act: "spin", need: "days"},
    {t: "{kid}，读题的时候我帮你竖着耳朵听。", act: "look", kid: 1},
    {t: "{kid}今天来看我啦，尾巴停不下来！", act: "giggle", kid: 1},
    {t: "陪你 {days} 天了，我又认识了好多数字。", act: "think", need: "days"},
  ],
  tap: [
    {t: "哎呀，好痒好痒！", act: "giggle"},
    {t: "你找我呀？嘿嘿，我在这儿！", act: "wave"},
    {t: "被戳到了！我弹起来啦～", act: "hop"},
    {t: "嗯？刚才是谁在敲门？", act: "look"},
    {t: "再戳一下，我就转个圈给你看", act: "spin"},
    {t: "嘿！你的手指头好暖和", act: "blink"},
    {t: "我刚打了个盹，被你叫醒啦", act: "yawn"},
    {t: "{kid}，你好呀，今天过得怎么样？", act: "wave"},
  ],
  tap_too_much: [
    {t: "哈哈哈停一停，我笑得要打嗝啦！", act: "giggle"},
    {t: "转转转……我变成陀螺啦，头好晕～", act: "spin"},
  ],
}
